### PR TITLE
openfoam : possible improvements for build

### PR DESCRIPTION
**Pull request by olesenm**
These reflect how we typically configure and build OpenFOAM for debian and rpm. See our [standard openfoam rpm template](https://develop.openfoam.com/Development/openfoam/-/wikis/packaging/common/openfoamVERSION.spec) as well as the [debian recipe](https://salsa.debian.org/olesenm/openfoam/-/blob/master/debian/rules#L161) for more details 

The configure command is the same that we also use in the [spack openfoam recipe](https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/openfoam/package.py).

Note that the changes proposed here have ***not yet been tested*** on an arch linux system, but I wanted to get them out there for discussion and possible integration.

FYI: @MakisH

/mark

### CODE REVIEW

**Comment by olesenm** [comment]
As mentioned in the comments section, might be reasonable to rename `openfoam-esi` to `openfoam-com` to reflect the source. Similarly rename `openfoam` to `openfoam-org`.

**Comment by petronny** [comment]
> Similarly rename `openfoam` to `openfoam-org` for the same reason.

Please help me check which distributions is naming the "com" version as as `openfoam`
and which are naming the "org" version as as `openfoam`,
according to https://repology.org/project/openfoam/versions .

**Comment by olesenm** [comment]
openfoam.com
- Debian testing
- Debian unstable 
- devuan 4.0
- devuan unstable 
- kali
- opensuse science
- parrot 
- pureos 
- raspbian testing
- Ubuntu 20.04
- Ubuntu 20.10

openfoam.org
- AUR
- Debian oldstable
- mageia
- parabola 
- raspbian oldstable
- slackbuilds
- Ubuntu 18.04

ancient
- deepin
- devuan 2.0
- funtoo
- guix
- pardus
- RPM sphere

**Comment by MakisH** [comment]
@olesenm these would be good comments for https://aur.archlinux.org/packages/openfoam-esi/, the upstream of this repository.

I am not the maintainer and I don't know if the `openfoam-esi` maintainer will look here.

**Comment by olesenm** [comment]
@dl6tud ?

**Comment by petronny** [comment]
58569566e258adb84e370228d44175fa67eae503

**Pull request closed without merging**
