### PR TITLE
Add linuxcnc-git

### PR DESCRIPTION
**Pull request by taotieren**
Learn Open Source CNC machining process

[linuxcnc-git.log](https://github.com/arch4edu/arch4edu/files/13692701/linuxcnc-git.log)

### CODE REVIEW

**Comment by petronny** [comment]
Hi, is there any particular reason to add the git version than the released version?

**Comment by petronny** [comment]
And you need to add the AUR makedepends ( `tclx` for `linuxcnc`, `tclx` and `tkimg` for `linuxcnc-git`) and list them in the `makedepends` field in `cactus.yaml`.

For `linuxcnc-git`, you also need to add the git upstream in the `nvchecker` field. And for `tkimg`, it further depends on tcllib so you need to also add it and list it in the `depends` (not `makedepends`) field in the `cactus.yaml` for `tkimg`.

A simpler way to solve these dependency issue is to use the `smart-add-package.py` script to add the final package then do some small tweaks to the `cactus.yaml`s.

**Comment by taotieren** [comment]
Thanks for your reply. smart-add-package.py Is there a detailed manual? Or dome examples?

**Comment by petronny** [comment]
See `python smart-add-package.py -h`.

Examples (may not work):
```sh
$ python smart-add-package.py -t template/x86_64-simple.yaml linuxcnc x86_64
$ vim x86_64/linuxcnc/cactus.yaml # to add the python upstream
```

```sh
$ python smart-add-package.py -t template/x86_64-simple.yaml linuxcnc-git x86_64
$ vim x86_64/linuxcnc-git/cactus.yaml # to add the python and git upstreams
```

**Comment by taotieren** [comment]
```bash

❯ python smart-add-package.py -t template/x86_64-simple.yaml linuxcnc-git x86_64/linuxcnc-git 
:: 正在同步软件包数据库...
 core 已经是最新版本
 extra 已经是最新版本
 multilib 已经是最新版本
 archlinuxcn 已经是最新版本
 aur-repo                    74.3 KiB  1281 KiB/s 00:00 [##############################] 100%
 blackarch 已经是最新版本
 arch4edu 已经是最新版本
 bioarchlinux 已经是最新版本
Traceback (most recent call last):
  File "/home/taotieren/git_clone/github.com/arch4edu/smart-add-package.py", line 102, in <module>
    provides = load_provides()
               ^^^^^^^^^^^^^^^
  File "/home/taotieren/git_clone/github.com/arch4edu/smart-add-package.py", line 65, in load_provides
    provides.update(read_provides('fuse2'))
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taotieren/git_clone/github.com/arch4edu/smart-add-package.py", line 55, in read_provides
    provides = [line for line in info if line.startswith('Provides')][0]
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

arch4edu on  linuxcnc-git via 🐍 v3.11.6 
❯ yay -Ss fuse2 
aur/azure-storage-fuse 2.1.0-1 (+2 0.00) (过时的: 2023-12-09) 
    A virtual file system adapter for Azure Blob storage (blobfuse2)
aur/lib32-fuse2 2.9.9-2 (+7 0.14) 
    A library that makes it possible to implement a filesystem in a userspace program (32 bit)
extra/fuse-common 3.16.2-1 (2.7 KiB 725.0 B) (已安装)
    Common files for fuse2/3 packages
core/fuse2fs 1.47.0-1 (29.2 KiB 67.5 KiB) (已安装)
    Ext2/3/4 filesystem driver for FUSE
extra/fuse2 2.9.9-4 (120.1 KiB 458.2 KiB) (已安装)
    A library that makes it possible to implement a filesystem in a userspace program.

```

**Comment by petronny** [comment]
Oops, please just remove that line to bypass this. I'll see what happens to the provide list of fuse2.

**Comment by petronny** [comment]
Hmmm, the script works as expected for me. Please dig a little deeper in the `read_provides` function (eg. print the `lines`) if you have time.

**Pull request merged**
