### PR TITLE
add x86_64/librealsense

### PR DESCRIPTION
**Pull request by Sir-Photch**

### CODE REVIEW

**Comment by petronny** [comment]
Hi, thanks for your contribution.

Only `cactus.yaml` is needed to add a package. Having `PKGBUILD` is OK but cactus will try to bump the pkgver and build `v2.53.1-3` instead of `v2.53.1-2`.

**Comment by Sir-Photch** [comment]
Sure, feel free to adjust this as required. Before creating this PR, I had a look at other packages and some of them came with a PKGBUILD, so I was not sure.

**Comment by petronny** [comment]
```yaml
depends:
  - x86_64/glfw-x11
  - x86_64/gtk3
```
are not needed. Only AUR dependencies should be listed here.

Locally building the package with `extra-x86_64-build` shows `glu` is needed but missing during the build.
This could be fixed by using the [add command in cactus](https://github.com/arch4edu/cactus/blob/main/builder/bin/add) and should be reported to the maintainer on AUR.

**Comment by Sir-Photch** [comment]
Thanks! I will keep this in mind when contributing again.

**Comment by petronny** [comment]
LGTM now. Please check the status in https://arch4edu.org/ in the next few days :).

**Pull request merged**
